/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guis;

/**
 *
 * @author mendi
 */
public class Genera_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Genera_Frame
     */
    public Genera_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPGeneral = new javax.swing.JTabbedPane();
        pnlMenu = new javax.swing.JPanel();
        btnRegistrarVenta = new javax.swing.JButton();
        btnAdministrarEmpleados = new javax.swing.JButton();
        btnAdministrarProductos = new javax.swing.JButton();
        lblMenuPrincipal = new javax.swing.JLabel();
        pnlCategorias = new javax.swing.JPanel();
        btnCatBebidas = new javax.swing.JButton();
        btnCatAlimentos = new javax.swing.JButton();
        btnCatCafeGrano = new javax.swing.JButton();
        btnCatPromociones = new javax.swing.JButton();
        lblCategorias = new javax.swing.JLabel();
        pnlProductos = new javax.swing.JPanel();
        jTPProductos = new javax.swing.JTabbedPane();
        pnlProductosBebidas = new javax.swing.JPanel();
        btnProBebChai = new javax.swing.JButton();
        btnProBebAmericano = new javax.swing.JButton();
        btnProBebExpresso = new javax.swing.JButton();
        btnProBebCapuccino = new javax.swing.JButton();
        btnProBebTe = new javax.swing.JButton();
        btnProBebChocolate = new javax.swing.JButton();
        btnProBebFrappe = new javax.swing.JButton();
        btnProBebCafeDia = new javax.swing.JButton();
        btnProBebLateada = new javax.swing.JButton();
        btnProBebAgua = new javax.swing.JButton();
        pnlDetalles = new javax.swing.JPanel();
        pnlCarrito = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));

        btnRegistrarVenta.setBackground(new java.awt.Color(193, 232, 213));
        btnRegistrarVenta.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnRegistrarVenta.setForeground(new java.awt.Color(91, 91, 91));
        btnRegistrarVenta.setText("Registrar Venta");
        btnRegistrarVenta.setBorder(null);
        btnRegistrarVenta.setBorderPainted(false);
        btnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVentaActionPerformed(evt);
            }
        });

        btnAdministrarEmpleados.setBackground(new java.awt.Color(193, 232, 213));
        btnAdministrarEmpleados.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnAdministrarEmpleados.setForeground(new java.awt.Color(91, 91, 91));
        btnAdministrarEmpleados.setText("Administrar Empleados");
        btnAdministrarEmpleados.setBorder(null);
        btnAdministrarEmpleados.setBorderPainted(false);
        btnAdministrarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarEmpleadosActionPerformed(evt);
            }
        });

        btnAdministrarProductos.setBackground(new java.awt.Color(193, 232, 213));
        btnAdministrarProductos.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnAdministrarProductos.setForeground(new java.awt.Color(91, 91, 91));
        btnAdministrarProductos.setText("Administrar Productos");
        btnAdministrarProductos.setBorder(null);
        btnAdministrarProductos.setBorderPainted(false);
        btnAdministrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarProductosActionPerformed(evt);
            }
        });

        lblMenuPrincipal.setFont(new java.awt.Font("Segoe UI Emoji", 0, 70)); // NOI18N
        lblMenuPrincipal.setForeground(new java.awt.Color(91, 91, 91));
        lblMenuPrincipal.setText("Menu Principal");

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(btnRegistrarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(btnAdministrarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(btnAdministrarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblMenuPrincipal)))
                .addContainerGap(351, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblMenuPrincipal)
                .addGap(72, 72, 72)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdministrarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdministrarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(528, Short.MAX_VALUE))
        );

        jTPGeneral.addTab("Menu", pnlMenu);

        pnlCategorias.setBackground(new java.awt.Color(255, 255, 255));

        btnCatBebidas.setBackground(new java.awt.Color(193, 232, 213));
        btnCatBebidas.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnCatBebidas.setForeground(new java.awt.Color(91, 91, 91));
        btnCatBebidas.setText("Bebidas");
        btnCatBebidas.setBorder(null);
        btnCatBebidas.setBorderPainted(false);
        btnCatBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatBebidasActionPerformed(evt);
            }
        });

        btnCatAlimentos.setBackground(new java.awt.Color(193, 232, 213));
        btnCatAlimentos.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnCatAlimentos.setForeground(new java.awt.Color(91, 91, 91));
        btnCatAlimentos.setText("Alimentos");
        btnCatAlimentos.setBorder(null);
        btnCatAlimentos.setBorderPainted(false);
        btnCatAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatAlimentosActionPerformed(evt);
            }
        });

        btnCatCafeGrano.setBackground(new java.awt.Color(193, 232, 213));
        btnCatCafeGrano.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnCatCafeGrano.setForeground(new java.awt.Color(91, 91, 91));
        btnCatCafeGrano.setText("Café en Grano");
        btnCatCafeGrano.setBorder(null);
        btnCatCafeGrano.setBorderPainted(false);
        btnCatCafeGrano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatCafeGranoActionPerformed(evt);
            }
        });

        btnCatPromociones.setBackground(new java.awt.Color(193, 232, 213));
        btnCatPromociones.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnCatPromociones.setForeground(new java.awt.Color(91, 91, 91));
        btnCatPromociones.setText("Promociones");
        btnCatPromociones.setBorder(null);
        btnCatPromociones.setBorderPainted(false);
        btnCatPromociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatPromocionesActionPerformed(evt);
            }
        });

        lblCategorias.setFont(new java.awt.Font("Segoe UI Emoji", 0, 70)); // NOI18N
        lblCategorias.setForeground(new java.awt.Color(91, 91, 91));
        lblCategorias.setText("Categorias de Producto");

        javax.swing.GroupLayout pnlCategoriasLayout = new javax.swing.GroupLayout(pnlCategorias);
        pnlCategorias.setLayout(pnlCategoriasLayout);
        pnlCategoriasLayout.setHorizontalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCategoriasLayout.createSequentialGroup()
                        .addGap(480, 480, 480)
                        .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCatBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCatCafeGrano, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCatPromociones, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCatAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCategoriasLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(613, Short.MAX_VALUE))
        );
        pnlCategoriasLayout.setVerticalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(lblCategorias)
                .addGap(73, 73, 73)
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCatBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCatAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCatCafeGrano, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCatPromociones, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(270, Short.MAX_VALUE))
        );

        jTPGeneral.addTab("Categorias", pnlCategorias);

        pnlProductos.setBackground(new java.awt.Color(255, 255, 255));

        pnlProductosBebidas.setBackground(new java.awt.Color(255, 255, 255));

        btnProBebChai.setBackground(new java.awt.Color(193, 232, 213));
        btnProBebChai.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnProBebChai.setForeground(new java.awt.Color(91, 91, 91));
        btnProBebChai.setText("Chai");
        btnProBebChai.setBorder(null);
        btnProBebChai.setBorderPainted(false);
        btnProBebChai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProBebChaiActionPerformed(evt);
            }
        });

        btnProBebAmericano.setBackground(new java.awt.Color(193, 232, 213));
        btnProBebAmericano.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnProBebAmericano.setForeground(new java.awt.Color(91, 91, 91));
        btnProBebAmericano.setText("Americano");
        btnProBebAmericano.setBorder(null);
        btnProBebAmericano.setBorderPainted(false);
        btnProBebAmericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProBebAmericanoActionPerformed(evt);
            }
        });

        btnProBebExpresso.setBackground(new java.awt.Color(193, 232, 213));
        btnProBebExpresso.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnProBebExpresso.setForeground(new java.awt.Color(91, 91, 91));
        btnProBebExpresso.setText("Expresso");
        btnProBebExpresso.setBorder(null);
        btnProBebExpresso.setBorderPainted(false);
        btnProBebExpresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProBebExpressoActionPerformed(evt);
            }
        });

        btnProBebCapuccino.setBackground(new java.awt.Color(193, 232, 213));
        btnProBebCapuccino.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnProBebCapuccino.setForeground(new java.awt.Color(91, 91, 91));
        btnProBebCapuccino.setText("Capuccino");
        btnProBebCapuccino.setBorder(null);
        btnProBebCapuccino.setBorderPainted(false);
        btnProBebCapuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProBebCapuccinoActionPerformed(evt);
            }
        });

        btnProBebTe.setBackground(new java.awt.Color(193, 232, 213));
        btnProBebTe.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnProBebTe.setForeground(new java.awt.Color(91, 91, 91));
        btnProBebTe.setText("Té");
        btnProBebTe.setBorder(null);
        btnProBebTe.setBorderPainted(false);
        btnProBebTe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProBebTeActionPerformed(evt);
            }
        });

        btnProBebChocolate.setBackground(new java.awt.Color(193, 232, 213));
        btnProBebChocolate.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnProBebChocolate.setForeground(new java.awt.Color(91, 91, 91));
        btnProBebChocolate.setText("Chocolate");
        btnProBebChocolate.setBorder(null);
        btnProBebChocolate.setBorderPainted(false);
        btnProBebChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProBebChocolateActionPerformed(evt);
            }
        });

        btnProBebFrappe.setBackground(new java.awt.Color(193, 232, 213));
        btnProBebFrappe.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnProBebFrappe.setForeground(new java.awt.Color(91, 91, 91));
        btnProBebFrappe.setText("Frappe");
        btnProBebFrappe.setBorder(null);
        btnProBebFrappe.setBorderPainted(false);
        btnProBebFrappe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProBebFrappeActionPerformed(evt);
            }
        });

        btnProBebCafeDia.setBackground(new java.awt.Color(193, 232, 213));
        btnProBebCafeDia.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnProBebCafeDia.setForeground(new java.awt.Color(91, 91, 91));
        btnProBebCafeDia.setText("Café del dia");
        btnProBebCafeDia.setBorder(null);
        btnProBebCafeDia.setBorderPainted(false);
        btnProBebCafeDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProBebCafeDiaActionPerformed(evt);
            }
        });

        btnProBebLateada.setBackground(new java.awt.Color(193, 232, 213));
        btnProBebLateada.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnProBebLateada.setForeground(new java.awt.Color(91, 91, 91));
        btnProBebLateada.setText("Lateada");
        btnProBebLateada.setBorder(null);
        btnProBebLateada.setBorderPainted(false);
        btnProBebLateada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProBebLateadaActionPerformed(evt);
            }
        });

        btnProBebAgua.setBackground(new java.awt.Color(193, 232, 213));
        btnProBebAgua.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnProBebAgua.setForeground(new java.awt.Color(91, 91, 91));
        btnProBebAgua.setText("Agua");
        btnProBebAgua.setBorder(null);
        btnProBebAgua.setBorderPainted(false);
        btnProBebAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProBebAguaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProductosBebidasLayout = new javax.swing.GroupLayout(pnlProductosBebidas);
        pnlProductosBebidas.setLayout(pnlProductosBebidasLayout);
        pnlProductosBebidasLayout.setHorizontalGroup(
            pnlProductosBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductosBebidasLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(pnlProductosBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlProductosBebidasLayout.createSequentialGroup()
                        .addComponent(btnProBebChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnProBebFrappe, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnProBebCafeDia, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnProBebLateada, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnProBebAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProductosBebidasLayout.createSequentialGroup()
                        .addComponent(btnProBebChai, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnProBebAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnProBebExpresso, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnProBebCapuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnProBebTe, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        pnlProductosBebidasLayout.setVerticalGroup(
            pnlProductosBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductosBebidasLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(pnlProductosBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProBebChai, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProBebAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProBebExpresso, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProBebCapuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProBebTe, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(pnlProductosBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProBebChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProBebFrappe, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProBebCafeDia, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProBebLateada, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProBebAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(392, Short.MAX_VALUE))
        );

        jTPProductos.addTab("Bebidas", pnlProductosBebidas);

        javax.swing.GroupLayout pnlProductosLayout = new javax.swing.GroupLayout(pnlProductos);
        pnlProductos.setLayout(pnlProductosLayout);
        pnlProductosLayout.setHorizontalGroup(
            pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 2049, Short.MAX_VALUE))
        );
        pnlProductosLayout.setVerticalGroup(
            pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPProductos)
                .addContainerGap())
        );

        jTPGeneral.addTab("Productos", pnlProductos);

        javax.swing.GroupLayout pnlDetallesLayout = new javax.swing.GroupLayout(pnlDetalles);
        pnlDetalles.setLayout(pnlDetallesLayout);
        pnlDetallesLayout.setHorizontalGroup(
            pnlDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2055, Short.MAX_VALUE)
        );
        pnlDetallesLayout.setVerticalGroup(
            pnlDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );

        jTPGeneral.addTab("Detalles", pnlDetalles);

        javax.swing.GroupLayout pnlCarritoLayout = new javax.swing.GroupLayout(pnlCarrito);
        pnlCarrito.setLayout(pnlCarritoLayout);
        pnlCarritoLayout.setHorizontalGroup(
            pnlCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2055, Short.MAX_VALUE)
        );
        pnlCarritoLayout.setVerticalGroup(
            pnlCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );

        jTPGeneral.addTab("Carrito", pnlCarrito);

        pnlHeader.setBackground(new java.awt.Color(222, 202, 184));

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPGeneral))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jTPGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarVentaActionPerformed

    private void btnAdministrarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdministrarEmpleadosActionPerformed

    private void btnAdministrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdministrarProductosActionPerformed

    private void btnCatBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatBebidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatBebidasActionPerformed

    private void btnCatAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatAlimentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatAlimentosActionPerformed

    private void btnCatCafeGranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatCafeGranoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatCafeGranoActionPerformed

    private void btnCatPromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatPromocionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatPromocionesActionPerformed

    private void btnProBebChaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProBebChaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProBebChaiActionPerformed

    private void btnProBebAmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProBebAmericanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProBebAmericanoActionPerformed

    private void btnProBebExpressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProBebExpressoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProBebExpressoActionPerformed

    private void btnProBebCapuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProBebCapuccinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProBebCapuccinoActionPerformed

    private void btnProBebTeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProBebTeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProBebTeActionPerformed

    private void btnProBebChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProBebChocolateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProBebChocolateActionPerformed

    private void btnProBebFrappeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProBebFrappeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProBebFrappeActionPerformed

    private void btnProBebCafeDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProBebCafeDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProBebCafeDiaActionPerformed

    private void btnProBebLateadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProBebLateadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProBebLateadaActionPerformed

    private void btnProBebAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProBebAguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProBebAguaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Genera_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Genera_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Genera_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Genera_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Genera_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrarEmpleados;
    private javax.swing.JButton btnAdministrarProductos;
    private javax.swing.JButton btnCatAlimentos;
    private javax.swing.JButton btnCatBebidas;
    private javax.swing.JButton btnCatCafeGrano;
    private javax.swing.JButton btnCatPromociones;
    private javax.swing.JButton btnProBebAgua;
    private javax.swing.JButton btnProBebAmericano;
    private javax.swing.JButton btnProBebCafeDia;
    private javax.swing.JButton btnProBebCapuccino;
    private javax.swing.JButton btnProBebChai;
    private javax.swing.JButton btnProBebChocolate;
    private javax.swing.JButton btnProBebExpresso;
    private javax.swing.JButton btnProBebFrappe;
    private javax.swing.JButton btnProBebLateada;
    private javax.swing.JButton btnProBebTe;
    private javax.swing.JButton btnRegistrarVenta;
    private javax.swing.JTabbedPane jTPGeneral;
    private javax.swing.JTabbedPane jTPProductos;
    private javax.swing.JLabel lblCategorias;
    private javax.swing.JLabel lblMenuPrincipal;
    private javax.swing.JPanel pnlCarrito;
    private javax.swing.JPanel pnlCategorias;
    private javax.swing.JPanel pnlDetalles;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlProductos;
    private javax.swing.JPanel pnlProductosBebidas;
    // End of variables declaration//GEN-END:variables
}
